name: Deploy MultiDocker
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t vladrimon/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true vladrimon/react-test npm test
 
      - run: docker build -t vladrimon/multi-client-11-19 ./client
      - run: docker build -t vladrimon/multi-nginx-11-19 ./nginx
      - run: docker build -t vladrimon/multi-server-11-19 ./server
      - run: docker build -t vladrimon/multi-worker-11-19 ./worker
 
      - run: docker push vladrimon/multi-client-11-19
      - run: docker push vladrimon/multi-nginx-11-19
      - run: docker push vladrimon/multi-server-11-19
      - run: docker push vladrimon/multi-worker-11-19
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-726740391201
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
